batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202308060824
train_epochs: 10
train_workers: 20
vocab: 5lBotrh*bf:?RMkU1iw3u&;4Y.LHAa,C82y#WKEqZG7zOVTF"eSs6Q!0/IN'xg)vmp9d+j-XPc(nJD
width: 128
